--- 
tag:
  "001": 
    predicate: RDF.type
    relation: 
      class: frbr:Manifestation
    object:
      regex: !ruby/regexp /[^\d]/
      prefix: http://redstore.deichman.no/resource/
      type: uri
      
  "008": 
    predicate: http://purl.org/dc/terms/language
    relation: 
      class: http://lexvo.org/ontology#Language
    object: 
      regex: !ruby/regexp /[34,3]/
      prefix: http://purl.org/dc/terms/language/
      type: uri

  "010": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/bibo/lccn
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          prefix: http://purl.org/ontology/bibo/lccn
          type: literal

  "019": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/audience
        object: 
          prefix: http://redstore.deichman.no/audience/
          regex: !ruby/regexp /[^A-z0-9\-]/
          type: uri
      b: 
        predicate: http://purl.org/dc/terms/format
        object:
          prefix: http://purl.org/dc/terms/format/
          regex: !ruby/regexp /[^A-z0-9\-]/
          split: !ruby/regexp /, */
          type: uri
      d: 
        predicate: http://bibpode.no/terms/literaryFormat
        object: 
          prefix: http://redstore.deichman.no/literaryFormat/
          regex: !ruby/regexp /[^A-z0-9\-]/
          type: uri

  "020": 
    subfield: 
      a: 
        conditions: 
          isbn10: 
            regex: if isbn.length == 10
            predicate: http://purl.org/ontology/bibo/isbn10
            object: 
              type: literal
          isbn13: 
            regex: if isbn.length == 13
            predicate: http://purl.org/ontology/bibo/isbn13
            object: 
              regex: !ruby/regexp /[\.:,;\/\s]\s*$/
              type: literal

  "022": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/bibo/issn
        object: 
          type: literal

  "035": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/bibo/oclcnum
        object: 
          regex: !ruby/regexp /^\\(OcoLC\\)/
          type: literal

  "041": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/language
        relation: 
          class: http://lexvo.org/ontology#Language
        object: 
          prefix: http://redstore.deichman.no/language/
          regex: !ruby/regexp /[^A-z0-9\-]/
          split: !ruby/regexp /(\w{3})/
          type: uri 

  "082": 
    subfield: 
      a: 
        predicate: http://bibpode.no/terms/ddk
        relation: 
          class: http://bibpode.no/terms/DDKCode
        object: 
          prefix: http://redstore.deichman.no/ddk/
          regex: !ruby/regexp /[^\S]/
          type: uri

  "090": 
    subfield: 
      ?
        - b
        - c
        - d
      : 
        predicate: http://bibpode.no/terms/location
        object: 
          type: literal

  "110": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/creator
        relation: 
          class: http://xmlns.com/foaf/0.1/Organization
          subfield: 
            a: 
              predicate: http://xmlns.com/foaf/0.1/name
              object: 
                type: literal
        object: 
          regex: !ruby/regexp /[^A-z0-9\-]/
          prefix: http://redstore.deichman.no/organization/
          type: uri

  "240": 
    subfield: 
      ?
        - a
        - b
      : 
        predicate: http://purl.org/dc/terms/alternative
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          type: literal

  "245": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/title
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          type: literal
      b: 
        predicate: http://rdvocab.info/Elements/variantTitleForTheWork
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          type: literal
      c: 
        predicate: http://RDVocab.info/Elements/statementOfResponsibility
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          type: literal
      n: 
        predicate: http://purl.org/ontology/bibo/number
        object: 
          regex: !ruby/regexp /[^\d]/
          type: integer

  "250": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/bibo/edition
        object: 
          regex: !ruby/regexp /[^\d]/
          type: integer

  "260": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/publicationPlace
        relation: 
          class: http://www.w3.org/2003/01/geo/wgs84_pos#Feature
        object: 
          regex: !ruby/regexp /[^A-z0-9\-]/
          prefix: http://redstore.deichman.no/publicationPlace/
          type: uri
      b: 
        predicate: http://purl.org/dc/terms/publisher
        relation: 
          class: http://xmlns.com/foaf/0.1/Organization
        object: 
          regex: !ruby/regexp /[^A-z0-9\-]/
          prefix: http://redstore.deichman.no/organization/
          type: uri
      c: 
        predicate: http://purl.org/dc/terms/issued
        object: 
          regex: !ruby/regexp /[^\d]/
          type: integer
          
  "300": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/bibo/pages
        object: 
          regex: !ruby/regexp /[^\d]/
          type: integer
      ?
        - b
        - c
        - e
      : 
        predicate: http://bibpode.no/terms/physicalDescription
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          type: literal

  "(246|767)": 
    subfield: 
      ?
        - a
        - b
        - c
        - e
        - t
      : 
        predicate: http://RDVocab.info/Elements/parallelTitleProper
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          type: literal

  "^5(?!71)": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/description
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          type: literal


  "571": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/bibo/identifier
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          type: literal

  "(100|400|700|790|796|800|896)": 
    subfield: 
      a:
        predicate: "http://purl.org/dc/terms/creator" 
        object: 
          type: uri
          prefix: "http://redstore.deichman.no/person/" 
          regex: !ruby/regexp /[^A-z0-9\-]/
        relation: 
          class: "http://xmlns.com/foaf/0.1/Person"
          subfield:
            a:
              predicate: "http://xmlns.com/foaf/0.1/name"
              object:
                type: literal
            b:
              predicate: "http://purl.org/ontology/bibo/suffixName"
              object:
                type: literal                
            c:
              predicate: "http://xmlns.com/foaf/0.1/title"
              object:
                type: literal
            d:
              predicate: "http://bibpode.no/terms/lifespan"
              object:
                type: literal
            j:
              predicate: "http://www.foafrealm.org/xfoaf/0.1/nationality"
              object:
                type: uri
                prefix: "http://redstore.deichman.no/nationality/"
                regex: !ruby/regexp /[\.:,;\/\s]\s*$/
            t:
              predicate: "http://purl.org/dc/terms/title"
              object:
                type: literal
      e:
        conditions: 
          reader:
            regex: /innl.*/
            predicate: http://bibpode.no/terms/reader
            object: 
              regex: !ruby/regexp /[^A-z0-9\-]/
              prefix: http://redstore.deichman.no/person/
              type: uri
          creator:
            regex: /medforf.*/
            predicate: http://purl.org/dc/terms/creator 
            object: 
              regex: !ruby/regexp /[^A-z0-9\-]/
              prefix: http://redstore.deichman.no/person/
              type: uri
          actor:
            regex: /reg.*/
            predicate: http://bibpode.no/terms/actor
            object: 
              regex: !ruby/regexp /[^A-z0-9\-]/
              prefix: http://redstore.deichman.no/person/
              type: uri
          translator:
            regex: /over.*/
            predicate: http://purl.org/ontology/bibo/translator
            object: 
              regex: !ruby/regexp /[^A-z0-9\-]/
              prefix: http://redstore.deichman.no/person/
              type: uri
       
  "440": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/isPartOf
        relation: 
          class: http://purl.org/ontology/bibo/Series
        object: 
          regex: !ruby/regexp /[^A-z0-9\-]/
          prefix: http://redstore.deichman.no/resource/
          type: uri
      v: 
        predicate: http://purl.org/ontology/bibo/pages
        object: 
          regex: !ruby/regexp /[^\\\\d]/
          type: integer
      x: 
        predicate: http://purl.org/ontology/bibo/issn
        object: 
          type: literal

  "600": 
    subfield: 
      ?
        - a
        - d
        - j
        - t
      : 
        predicate: http://purl.org/dc/terms/subject
        object: 
          regex: !ruby/regexp /[^A-z0-9\-]/
          prefix: http://redstore.deichman.no/subject/
          type: uri
        relation: 
          class: http://www.w3.org/2004/02/skos/core#Concept


  "(650|690|693|699)": 
    subfield: 
      ?
        - a
        - d
        - j
      : 
        predicate: http://purl.org/dc/terms/subject
        object: 
          regex: !ruby/regexp /[^A-z0-9\-]/
          prefix: http://redstore.deichman.no/subject/
          type: uri
        relation: 
          class: http://www.w3.org/2004/02/skos/core#Concept
          subfield: 
            x: 
              predicate: http://purl.org/dc/terms/subject
              relation: 
                class: http://bibpode.no/terms/DDKCode2
              object: 
                regex: !ruby/regexp /[^A-z0-9\-]/
                prefix: http://redstore.deichman.no/classification/
                type: uri              
            1: 
              predicate: http://redstore.deichman.no/classification
              relation: 
                class: http://bibpode.no/terms/DDKCode
              object: 
                regex: !ruby/regexp /[^A-z0-9\-]/
                prefix: http://redstore.deichman.no/ddk/
                type: uri

  "652": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/mo/genre
        relation: 
          class: http://purl.org/ontology/mo/Genre
        object: 
          regex: !ruby/regexp /[^A-z0-9\-]/
          prefix: http://redstore.deichman.no/mogenre/
          type: uri

  "655": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/mv/genre
        relation: 
          class: http://purl.org/ontology/mo/Genre
        object: 
          regex: !ruby/regexp /[^A-z0-9\-]/
          prefix: http://redstore.deichman.no/mvgenre/
          type: uri
  "710": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/creator
        relation: 
          class: http://xmlns.com/foaf/0.1/Organization
        object: 
          regex: !ruby/regexp /[^A-z0-9\-]/
          prefix: http://redstore.deichman.no/organization/
          type: uri


  "760": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/isPartOf
        relation: 
          class: http://purl.org/ontology/bibo/Series
        object: 
          regex: !ruby/regexp /[^A-z0-9\-]/
          prefix: http://redstore.deichman.no/resource/
          type: uri

  "730": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/alternative
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          type: literal
 
