---
substitutes: {'Æ': Ae,  'Ø': Oe,  'Å': Aa,  'æ': ae,  'ø': oe,  'å': aa,  'Ä': Ae,  'Ö': Oe,  'ä': ae, 'ö': oe,  ' ': '_', 'é': e, 'è': e, 'ê': e, 'á': a, 'à': a, 'â': a, 'ã': a, 'í': i, 'ì': i, 'î': i, 'ĩ': i, 'ó': o, 'ò': o, 'ô': o, 'õ': o, 'ú': u, 'ù': u, 'û': u, 'ũ': u}

tag:
  "001": 
    predicate: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
    object:
      regex_strip: "[\D]+"
      prefix: http://rdf.deichman.no/resource/
      datatype: uri
    relation: 
      class: http://purl.org/vocab/frbr/core#Manifestation
      
  "008": 
    predicate: http://purl.org/dc/terms/language
    object: 
      regex_strip: "^{34}{3}"
      prefix: http://lexvo.org/id/iso639-3/
      datatype: uri
    relation: 
      class: http://lexvo.org/ontology#Language

  "010": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/bibo/lccn
        object: 
          regex_strip: "[\.:,;\/\s]\s*$"
          prefix: http://rdf.deichman.no/bibo/lccn/
          datatype: literal

  "019": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/audience
        object: 
          prefix: http://rdf.deichman.no/audience/
          regex_strip: "[\W]+"
          datatype: uri
      b: 
        predicate: http://purl.org/dc/terms/format
        object:
          prefix: http://rdf.deichman.no/format/
          regex_strip: "[\W]+"
          regex_split: ", *"
          datatype: uri
      d: 
        predicate: http://bibpode.no/terms/literaryFormat
        object: 
          prefix: http://rdf.deichman.no/literaryFormat/
          regex_strip: "[\W]+"
          datatype: uri

  "020": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/bibo/isbn
        object: 
          regex_strip: "[\D]+"
          datatype: literal

  "022": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/bibo/issn
        object:
          regex_strip: "[\D]+"
          datatype: literal

  "035": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/bibo/oclcnum
        object: 
          regex_strip: "^\(OcoLC\)"
          datatype: literal

  "041": 
    subfield: 
      a: 
        predicate: http://lexvo.org/ontology#marcCode
        object: 
          prefix: http://lexvo.org/id/iso639-3/
          regex_strip: "[\W]+"
          regex_split: "(\w{3})"
          datatype: uri 
        relation: 
          class: http://lexvo.org/ontology#Language
                
  "082": 
    subfield: 
      a: 
        predicate: http://bibpode.no/terms/ddk
        object: 
          prefix: http://rdf.deichman.no/ddk/
          regex_strip: "[\W\.]+"
          datatype: uri
        relation: 
          class: http://bibpode.no/terms/DDKCode

  "090": 
    subfield: 
      ?
        - b
        - c
        - d
      : 
        predicate: http://purl.org/dc/terms/location
        object: 
          datatype: literal
          lang: :no

  "110": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/creator
        object:
          regex_replace: "Å|Ø|Æ|å|ø|æ|Ä|Ö|ä|ö|\ |[éèêẽ]|[áàâã]|[íìîĩ]|[óòôõ]|[úùûũ]" 
          regex_strip: "[\W]+"
          prefix: http://rdf.deichman.no/organization/
          datatype: uri
        relation: 
          class: http://xmlns.com/foaf/0.1/Organization
          subfield: 
            a: 
              predicate: http://xmlns.com/foaf/0.1/name
              object: 
                datatype: literal
                lang: :no

  "240": 
    subfield: 
      ?
        - a
        - b
      : 
        predicate: http://purl.org/dc/terms/alternative
        object: 
          regex_strip: "[\.:,;\/\s]\s*$"
          datatype: literal

  "245": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/title
        object: 
          regex_strip: "[\.:,;\/\s]\s*$"
          datatype: literal
      b: 
        predicate: http://rdvocab.info/Elements/variantTitleForTheWork
        object: 
          regex_strip: "[\.:,;\/\s]\s*$"
          datatype: literal
      c: 
        predicate: http://RDVocab.info/Elements/statementOfResponsibility
        object: 
          regex_strip: "[\.:,;\/\s]\s*$"
          datatype: literal
      n: 
        predicate: http://purl.org/ontology/bibo/number
        object: 
          regex_strip: "[\D]+"
          datatype: integer

  "250": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/bibo/edition
        object: 
          regex_strip: "[\D]+"
          datatype: integer

  "260": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/publicationPlace
        object: 
          regex_replace: "Å|Ø|Æ|å|ø|æ|Ä|Ö|ä|ö|\ |[éèêẽ]|[áàâã]|[íìîĩ]|[óòôõ]|[úùûũ]"
          regex_strip: "[\W]+"
          prefix: http://rdf.deichman.no/publicationPlace/
          datatype: uri
        relation: 
          class: "http://www.geonames.org/ontology#Feature"
          subfield:
            a:
              predicate: "http://www.geonames.org/ontology#name"
              object:
                datatype: literal
                lang: :no
      b: 
        predicate: http://purl.org/dc/terms/publisher
        object: 
          regex_replace: "Å|Ø|Æ|å|ø|æ|Ä|Ö|ä|ö|\ |[éèêẽ]|[áàâã]|[íìîĩ]|[óòôõ]|[úùûũ]"
          regex_strip: "[\W]+"
          prefix: http://rdf.deichman.no/organization/
          datatype: uri
        relation: 
          class: http://xmlns.com/foaf/0.1/Organization
          subfield:
            b:
              predicate: "http://xmlns.com/foaf/0.1/name"
              object:
                datatype: literal
                lang: :no
      c: 
        predicate: http://purl.org/dc/terms/issued
        object: 
          regex_strip: "[\D]+"
          datatype: integer
          
  "300": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/bibo/numPages
        object: 
          regex_strip: "[\D]+"
          datatype: integer
      ?
        - b
        - c
        - e
      : 
        predicate: http://bibpode.no/terms/physicalDescription
        object: 
          regex_strip: "^[\W]+[\W]+$"
          datatype: literal
          lang: :no

  "(246|767)": 
    subfield: 
      ?
        - a
        - b
        - c
        - e
        - t
      : 
        predicate: http://RDVocab.info/Elements/parallelTitleProper
        object: 
          regex_strip: "^[\W]+[\W]+$"
          datatype: literal
          lang: :no

  "^5(?!71)": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/description
        object: 
          regex_strip: "^[\W]+[\W]+$"
          datatype: literal
          lang: :no

  "571": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/bibo/identifier
        object: 
          regex_strip: "^[\W]+[\W]+$"
          datatype: literal

  "(100|400|700|790|796|800|896)": 
    subfield: 
      a:
        predicate: "http://purl.org/dc/terms/creator" 
        object: 
          datatype: uri
          prefix: "http://rdf.deichman.no/person/" 
          regex_replace: "Å|Ø|Æ|å|ø|æ|Ä|Ö|ä|ö|\ |[éèêẽ]|[áàâã]|[íìîĩ]|[óòôõ]|[úùûũ]"
          regex_strip: "[\W]+"
        relation: 
          class: "http://xmlns.com/foaf/0.1/Person"
          subfield:
            a:
              predicate: "http://xmlns.com/foaf/0.1/name"
              object:
                datatype: literal
            b:
              predicate: "http://purl.org/ontology/bibo/suffixName"
              object:
                datatype: literal                
            c:
              predicate: "http://xmlns.com/foaf/0.1/title"
              object:
                datatype: literal
                lang: :no
            d:
              predicate: "http://bibpode.no/terms/lifespan"
              object:
                datatype: literal
            j:
              predicate: "http://www.foafrealm.org/xfoaf/0.1/nationality"
              object:
                datatype: uri
                prefix: "http://rdf.deichman.no/nationality/"
                regex_strip: "[\W]+"
            t:
              predicate: "http://purl.org/dc/terms/title"
              object:
                datatype: literal
                lang: :no
      e:
        conditions: 
          reader:
            regex_strip: "innl.*"
            predicate: http://bibpode.no/terms/reader
            object: 
              regex_strip: "[\W]+"
              prefix: http://rdf.deichman.no/person/
              datatype: uri
          creator:
            regex_strip: "medforf.*"
            predicate: http://purl.org/dc/terms/creator 
            object: 
              regex_strip: "[\W]+"
              prefix: http://rdf.deichman.no/person/
              datatype: uri
          actor:
            regex_strip: "reg.*"
            predicate: http://bibpode.no/terms/actor
            object: 
              regex_strip: "[\W]+"
              prefix: http://rdf.deichman.no/person/
              datatype: uri
          translator:
            regex_strip: "over.*"
            predicate: http://purl.org/ontology/bibo/translator
            object: 
              regex_strip: "[\W]+"
              prefix: http://rdf.deichman.no/person/
              datatype: uri
       
  "440": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/isPartOf
        object: 
          regex_strip: "[\W]+"
          prefix: http://rdf.deichman.no/resource/
          datatype: uri
        relation: 
          class: http://purl.org/ontology/bibo/Series
      v: 
        predicate: http://purl.org/ontology/bibo/numPages
        object: 
          regex_strip: "[\D]+"
          datatype: integer
      x: 
        predicate: http://purl.org/ontology/bibo/issn
        object: 
          datatype: literal

  "600": 
    subfield: 
      ?
        - a
        - d
        - j
        - t
      : 
        predicate: http://purl.org/dc/terms/subject
        object:
          regex_replace: "Å|Ø|Æ|å|ø|æ|Ä|Ö|ä|ö|\ |[éèêẽ]|[áàâã]|[íìîĩ]|[óòôõ]|[úùûũ]" 
          regex_strip: "[\W\-]+"
          prefix: http://rdf.deichman.no/subject/
          datatype: uri
        relation: 
          class: http://www.w3.org/2004/02/skos/core#Concept
          subfield: 

  "(650|690|693|699)": 
    subfield: 
      ?
        - a
        - d
        - j
      : 
        predicate: http://purl.org/dc/terms/subject
        object:
          regex_replace: "Å|Ø|Æ|å|ø|æ|Ä|Ö|ä|ö|\ |[éèêẽ]|[áàâã]|[íìîĩ]|[óòôõ]|[úùûũ]"
          regex_strip: "[\W\-]+"
          regex_split: ", *"
          prefix: http://rdf.deichman.no/subject/
          datatype: uri
        relation: 
          class: http://www.w3.org/2004/02/skos/core#Concept
          subfield:
            a: 
              predicate: http://www.w3.org/2004/02/skos/core#prefLabel
              object: 
                datatype: literal
                lang: :no
            x: 
              predicate: http://purl.org/dc/terms/subject
              object: 
                regex_replace: "Å|Ø|Æ|å|ø|æ|Ä|Ö|ä|ö|\ |[éèêẽ]|[áàâã]|[íìîĩ]|[óòôõ]|[úùûũ]"
                regex_strip: "[\W\-\.]+"
                prefix: http://rdf.deichman.no/classification/
                datatype: uri
              relation: 
                class: http://bibpode.no/terms/DDKCode
            1: 
              predicate: http://rdf.deichman.no/classification
              object: 
                regex_replace: "Å|Ø|Æ|å|ø|æ|Ä|Ö|ä|ö|\ |[éèêẽ]|[áàâã]|[íìîĩ]|[óòôõ]|[úùûũ]"
                regex_strip: "[\W\-\.]+"
                prefix: http://rdf.deichman.no/ddk/
                datatype: uri
              relation: 
                class: http://bibpode.no/terms/DDKCode

  "652": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/mo/genre
        object: 
          regex_replace: "Å|Ø|Æ|å|ø|æ|Ä|Ö|ä|ö|\ |[éèêẽ]|[áàâã]|[íìîĩ]|[óòôõ]|[úùûũ]"
          regex_strip: "[\W]+"
          prefix: http://rdf.deichman.no/mogenre/
          datatype: uri
        relation: 
          class: http://purl.org/ontology/mo/Genre
          subfield:
            a: 
              predicate: http://www.w3.org/2004/02/skos/core#prefLabel
              object: 
                datatype: literal
                lang: :no

  "655": 
    subfield: 
      a: 
        predicate: http://purl.org/ontology/mo/genre
        object: 
          regex_replace: "Å|Ø|Æ|å|ø|æ|Ä|Ö|ä|ö|\ |[éèêẽ]|[áàâã]|[íìîĩ]|[óòôõ]|[úùûũ]"
          regex_strip: "[\W\-]+"
          prefix: http://rdf.deichman.no/mogenre/
          datatype: uri
        relation: 
          class: http://purl.org/ontology/mo/Genre
          subfield:
            a: 
              predicate: http://www.w3.org/2004/02/skos/core#prefLabel
              object: 
                datatype: literal
                lang: :no

  "710": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/creator
        object: 
          regex_replace: "Å|Ø|Æ|å|ø|æ|Ä|Ö|ä|ö|\ |[éèêẽ]|[áàâã]|[íìîĩ]|[óòôõ]|[úùûũ]"
          regex_strip: "[\W\-]+"
          prefix: http://rdf.deichman.no/organization/
          datatype: uri
        relation: 
          class: http://xmlns.com/foaf/0.1/Organization
          subfield:
            a:
              predicate: "http://xmlns.com/foaf/0.1/name"
              object:
                datatype: literal
                lang: :no


  "760": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/isPartOf
        object:
          regex_strip: "[\W\-]+"
          prefix: http://rdf.deichman.no/resource/
          datatype: uri
        relation: 
          class: http://purl.org/ontology/bibo/Series
          subfield:
            a:          
              predicate: http://purl.org/ontology/bibo/edition
              object: 
                datatype: literal
                lang: :no          
  "730": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/alternative
        object: 
          regex_strip: "^[\W]+[\W]+$"
          datatype: literal
 
