--- 
tag:
  "856": 
    subfield: 
      u:
        predicate: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
        relation: 
          class: http://purl.org/ontology/bibo/Image
        object:
          regex: !ruby/regexp /.*[/\\\\]/
          prefix: http://bildebaser.deichman.no/image/
          datatype: uri

  "245": 
    subfield: 
      a: 
        predicate: http://purl.org/dc/terms/title
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          datatype: literal
          lang: :no

  "260": 
    subfield: 
      c: 
        predicate: http://purl.org/dc/terms/created
        object: 
          regex: !ruby/regexp /[^\d]/
          datatype: integer
          
  "300": 
    subfield: 
      b: 
        predicate: http://rdvocab.info/Elements/colourOfStillImage
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          datatype: literal
          lang: :no          

  "500":
    subfield:
      a:
        predicate: http://rdvocab.info/Elements/noteOnPublicationStatement
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          datatype: literal
          lang: :no

  "505":
    subfield:
      a:
        predicate: http://purl.org/dc/terms/description
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          datatype: literal
          lang: :no
          
  "593":
    subfield:
      a:
        predicate: http://purl.org/dc/terms/rights
        object: 
          regex: !ruby/regexp /[\.:,;\/\s]\s*$/
          datatype: literal
          lang: :no
          
  "600": 
    subfield: 
      a:
        predicate: http://xmlns.com/foaf/0.1/depicts
        object: 
          regex: !ruby/regexp /[^\w\-ÆØÅæøå]/
          prefix: http://bildebaser.deichman.no/agent/
          datatype: uri
        relation: 
          class: "http://xmlns.com/foaf/0.1/Agent"
          subfield:
            a:
              predicate: "http://xmlns.com/foaf/0.1/name"
              object:
                datatype: literal
                lang: :no
            c:
              predicate: "http://purl.org/dc/terms/description"
              object:
                datatype: literal
                lang: :no
            u:
              predicate: "http://purl.org/dc/terms/description"
              object:
                regex: !ruby/regexp /[\.:,;\/\s]\s*$/
                datatype: literal
                lang: :no
            y:
              predicate: "http://xmlns.com/foaf/0.1/title"
              object:
                regex: !ruby/regexp /[\.:,;\/\s]\s*$/
                datatype: literal
                lang: :no

  "610": 
    subfield: 
      a:
        predicate: http://xmlns.com/foaf/0.1/depicts
        object: 
          regex: !ruby/regexp /[^\w\-ÆØÅæøå]/
          prefix: http://bildebaser.deichman.no/agent/
          datatype: uri
        relation: 
          class: "http://xmlns.com/foaf/0.1/Agent"
          subfield:
            a:
              predicate: "http://xmlns.com/foaf/0.1/name"
              object:
                datatype: literal
                lang: :no

  "650":
    subfield:
      a:
        predicate: http://purl.org/dc/terms/subject
        object:
          regex: !ruby/regexp /[^\w\-ÆØÅæøå]/
          prefix: http://bildebaser.deichman.no/subject/
          datatype: uri
        relation:
          class: http://www.w3.org/2004/02/skos/core#Concept
          subfield: 
            a: 
              predicate: http://www.w3.org/2004/02/skos/core#prefLabel
              object: 
                datatype: literal
                lang: :no

  "690": 
    subfield: 
      a:
        predicate: http://xmlns.com/foaf/0.1/depicts
        object: 
          regex: !ruby/regexp /[^\w\-ÆØÅæøå]/
          prefix: http://bildebaser.deichman.no/place/
          datatype: uri
        relation: 
          class: "http://www.geonames.org/ontology#Feature"
          subfield:
            a:
              predicate: "http://www.geonames.org/ontology#name"
              object:
                datatype: literal
                lang: :no
      b:
        predicate: http://xmlns.com/foaf/0.1/depicts
        object: 
          regex: !ruby/regexp /[^\w\-ÆØÅæøå]/
          prefix: http://bildebaser.deichman.no/place/
          datatype: uri
        relation: 
          class: "http://www.geonames.org/ontology#Feature"
          subfield:
            a:
              predicate: "http://www.geonames.org/ontology#name"
              object:
                datatype: literal
                lang: :no

  "(700|710)": 
    subfield: 
      a:
        predicate: "http://purl.org/dc/terms/creator" 
        object: 
          datatype: uri
          prefix: "http://bildebaser.deichman.no/agent/" 
          regex: !ruby/regexp /[^\w\-ÆØÅæøå]/
        relation: 
          class: "http://xmlns.com/foaf/0.1/Agent"
          subfield:
            a:
              predicate: "http://xmlns.com/foaf/0.1/name"
              object:
                datatype: literal
                lang: :no

  "(702|712)": 
    subfield: 
      a:
        predicate: "http://rdvocab.info/Elements/immediateSourceOfAcquisitionOfItem" 
        object: 
          datatype: uri
          prefix: "http://bildebaser.deichman.no/agent/" 
          regex: !ruby/regexp /[^\w\-ÆØÅæøå]/
        relation: 
          class: "http://xmlns.com/foaf/0.1/Agent"
          subfield:
            a:
              predicate: "http://xmlns.com/foaf/0.1/name"
              object:
                datatype: literal
                lang: :no

  "703": 
    subfield: 
      a:
        predicate: "http://rdvocab.info/Elements/sourceConsulted" 
        object: 
          datatype: uri
          prefix: "http://bildebaser.deichman.no/agent/" 
          regex: !ruby/regexp /[^\w\-ÆØÅæøå]/
        relation: 
          class: "http://xmlns.com/foaf/0.1/Agent"
          subfield:
            a:
              predicate: "http://xmlns.com/foaf/0.1/name"
              object:
                datatype: literal
                lang: :no

  "725": 
    subfield: 
      a:
        predicate: "http://purl.org/dc/terms/rightsHolder" 
        object: 
          datatype: uri
          prefix: "http://bildebaser.deichman.no/agent/" 
          regex: !ruby/regexp /[^\w\-ÆØÅæøå]/
        relation: 
          class: "http://xmlns.com/foaf/0.1/Agent"
          subfield:
            a:
              predicate: "http://xmlns.com/foaf/0.1/name"
              object:
                datatype: literal
                lang: :no
